debug = false
BEST_CURRENCIES = false
BOT_DELAY = 1
BOT_CCLEAN = 2
CANCEL_ORDERS_ENABLED = true
CANCEL_ORDERS_CYCLE_CAP = 1
RESERVE_PILE_UP = false
interval_ticker_update = 25000
period_storage_ticker = 2000
timeout_buy = 60000
timeout_sell = 60000
PYRAMID_BUY = true
TRADING_LIMIT_BUY_PYRAMID = 0.01
TV_GAIN = 0.6
TV_TRADING_LIMIT_BUY = 0.001
TV_TRADING_LIMIT_BUY_PYRAMID = 0.001
TV_PYRAMID = true
TV_TRADING_LIMIT_SELL = 0.001
TV_PROTECTION = false
TV_TRADING_LIMIT_CAP = 0.0001
TV_STOPLOSS_PERCENTAGE = 60
RETRY_TV_ORDER = false
VERBOSE = true
WATCH_MODE = false
MINIMUM_VOLUME_GOOD_CURRENCY = 200
MINIMUM_VARIATION_SUGGEST_TRADE = 1
withdraw_address = "YOURBTCADDRESSHERE"
withdraw_threshold = 0.5
TELEGRAM_ENABLED = true
TELEGRAM_NICK = "Gunbot"
TOKEN = "YOURTOKENHERE"
chat_id = 123456
