enabled = false
authorized_froms = "[\"noreply@tradingview.com\"]"
user = "YOUR_EMAIL_HERE"
password = "YOUR_PASSWORD_HERE"
host = "imap.gmail.com"
port = 993
tls = true

[tlsOptions]
rejectUnauthorized = false
